### ISSUE TITLE
 [BUG] Symlink to sap__types is deleted after each npm command

### ISSUE THREAD

**Issue by levkovsb** [cap-js/cds-types#251] opened 2024-09-24 12:48 UTC
The issue persists in the version 0.6.5. As long as I execute any npm script in one of the workspaces of our monorepo, the symlink is gone and the project is no longer runnable. Please investigate further

_Originally posted by @levkovsb in https://github.com/cap-js/cds-types/issues/216#issuecomment-2371170882_

**Comment by daogrady** [comment] 2024-09-24 13:14
Hi @levkovsb ,

thanks for bringing this up again. Can you run `npm rebuild` in your repository and see if that recreates the symlink?

Best,
Daniel

**Comment by daogrady** [comment] 2024-10-02 06:42
@levkovsb also, can you please describe your setup in more detail or, preferably, provide a minimal reproduction setup? Is cds-types referenced in the mono repo root or in one of the subprojects?

**Comment by Markus-Schroeder-de** [comment] 2024-10-22 19:08
The symlink is often deleted. if i call mtb build, afterwards it is gone (because it calls npm i). "npm repair" does the magic.

**Comment by daogrady** [comment] 2024-10-24 11:55
Hi @levkovsb ,

as @Markus-Schroeder-de suggested, you can try `npm repair` to see if that fixes the symlink.
Could you elaborate why you don't just reference `@cap-js/cds-types` in each project's `devDependency` list?

Best,
Daniel

**Comment by ZhongpinWang** [comment] 2024-11-11 09:06
Hi @daogrady ,

Thanks for pointing me to this issue. We are facing the same issue. I have already written the description in https://github.com/cap-js/cds-types/issues/294#issuecomment-2464690467.

But just for a quick summary also here. We sometimes face the following problem:

```
Could not find a declaration file for module '@sap/cds'. '****/ai-sdk-js/node_modules/.pnpm/@sap+cds@8.4.1_express@4.21.1/node_modules/@sap/cds/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/sap__cds` if it exists or add a new declaration (.d.ts) file containing `declare module '@sap/cds';`ts(7016)
```

This error is flaky. I am not sure when will this happen. But maybe by deleting the `node_modules` and try `pnpm install` can trigger this. (I suppose both `pnpm` and `npm` have the same problem). With a `pnpm rebuild`, the problem is gone. 

Also sometimes, a fresh install in our pipeline works, but sometimes the symlink is missing. Re-trigger the pipeline and the problem can sometimes be gone. 

We are also maintaining multiple packages in one repo. The interesting thing I find is that putting `@cap-js/cds-types` as `devDependencies` in one package will actually result into a symlink in the root `node_modules`, which sometimes links to nowhere.

Hope this issue can be resolved soon.

**Comment by hakimio** [comment] 2024-11-11 15:40
Might be an issue with the way `pnpm` sets `INIT_CWD` environment variable: https://github.com/pnpm/pnpm/issues/7042
Also, experienced this issue where `cds` types could no longer be found after migrating from `yarn` to `pnpm`.
As a temporary workaround, I've added `cap-js/cds-types` to `tsconfig`:
```json
{
    "compilerOptions": {
        /* ... */
        "types": [
            "./typings.d.ts",
            "@cap-js/cds-types"
        ]
    }
}
```

**Comment by daogrady** [comment] 2024-11-13 12:32
Hi @ZhongpinWang ,

I checked your repository and the similarity with @levkovsb seems to be that you are also using a monorepo.
So same question here: you do not reference `@cap-js/cds-types` in each workspace. Could you try specifying `@cap-js/cds-types` as dependency and try again? The dependency can be very lax, e.g. `"@cap-js/cds-types": "*"`.

Best,
Daniel

P.S.: in the meanwhile, the suggestion @hakimio brought up is a perfectly valid solution.

**Comment by daogrady** [comment] 2024-12-18 07:52
Closing as quasi-duplicate of https://github.com/cap-js/cds-types/issues/318

**Closed by daogrady** 2024-12-18 07:52 UTC
