### ISSUE TITLE
[QUESTION] Why entity.association('*') is not same as entity?.association?.('*') in cds-typer?

### ISSUE THREAD

**Issue by ThePlenkov** [cap-js/cds-types#223] opened 2024-09-05 08:11 UTC
### Question

HI! I have q very weird issue in my project.

Let's say i have a code like this:
```ts
const result = await SELECT.from(OBJECTS, (o) => {
    o.OBJECT_TYPE, o.OBJECT_OID, o.SCHEMA_NAME, o.OBJECT_NAME;
    o.view &&
      o.view((v) => {
        v('*');
        v.columns('*');
      });
```

By default it won't run because of the TS error:
```
Cannot invoke an object which is possibly 'undefined'.ts(2722)
(property) columns?: cds.ql.QLExtensions_<VIEW_COLUMNS_> | undefined
```

So here are two possible ways how to solve it:

- using condition
```
 o.view((v) => {
        v('*');
        v.columns && v.columns('*');
      });
```

and it works 

- using optional notation ( also preferred by AI )

```
  o.view &&
      o.view((v) => {
        v('*');
        v?.columns?.('*');
      });
```

and this doesn't work!

Here is what I have in the console:
```
/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:876
        throw new Error(
              ^
Error: "call" not found in the elements of "VIEWS"
    at stepNotFoundInCombinedElements (/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:876:15)
    at /workspace/node_modules/@cap-js/db-service/lib/infer/index.js:576:13
    at Array.forEach (<anonymous>)
    at inferQueryElement (/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:529:18)
    at handleRef (/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:453:7)
    at /workspace/node_modules/@cap-js/db-service/lib/infer/index.js:331:16
    at Array.forEach (<anonymous>)
    at inferQueryElements (/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:300:15)
    at infer (/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:71:22)
    at resolveExpand (/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:842:42)
```

Do you know why? Thank you!

**Comment by daogrady** [comment] 2024-09-05 08:19
Hi Petr,

thanks for filing this issue. I have transferred it to https://github.com/cap-js/cds-types as this is likely related to the types for the cds runtime, and probably has nothing to do with the generation of types for your model (cds-typer).

Can you share the type definition of `OBJECTS`?

Best,
Daniel

**Comment by ThePlenkov** [comment] 2024-09-05 08:28
@daogrady  THank you for looking into the issue. Types are generated - you can see them in a published package: https://www.npmjs.com/package/hana2cds?activeTab=code

Here is the source:
https://github.com/sapops/hana-cli/tree/main/packages/hana2cds/src/cds

Here is the place causing the error:
https://github.com/sapops/hana-cli/blob/main/packages/hana2cds/src/lib/hana2csn.ts#L22

**Comment by daogrady** [comment] 2024-09-05 12:02
@sjvans / @johannes-vogel 
user code looks fine on first glance. Nested projections should be allowed:

```js
o.view((v /* type: { columns: Association to many { ... } } */) => {
  v('*');
  v?.columns?.('*');
});
```

the error seems to be thrown at runtime from the db-service module (see stacktrace in original post). Could you please have a look? Thanks!

**Comment by sjvans** [comment] 2024-09-09 12:16
@patricebender should be able to assist

**Comment by patricebender** [comment] 2024-09-09 13:59
Hi @ThePlenkov,

please provide steps to reproduce the error:

```
/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:876
        throw new Error(
              ^
Error: "call" not found in the elements of "VIEWS"
    at stepNotFoundInCombinedElements (/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:876:15)
    at /workspace/node_modules/@cap-js/db-service/lib/infer/index.js:576:13
    at Array.forEach (<anonymous>)
    at inferQueryElement (/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:529:18)
    at handleRef (/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:453:7)
    at /workspace/node_modules/@cap-js/db-service/lib/infer/index.js:331:16
    at Array.forEach (<anonymous>)
    at inferQueryElements (/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:300:15)
    at infer (/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:71:22)
    at resolveExpand (/workspace/node_modules/@cap-js/db-service/lib/infer/index.js:842:42)
```

Thank you
Patrice

**Comment by ThePlenkov** [comment] 2024-09-09 15:47
@patricebender Hi Patrcie, of course. Here it is:
- clone https://github.com/ThePlenkov/sample-cap-cds-isssue
- npm install
- npm test

You will see that there will be two tests, one is working ( with conditional guards ) and one is not working with optional notation.

**Comment by patricebender** [comment] 2024-09-10 11:28
@ThePlenkov thanks for providing the sample, I was able to reproduce the issue.

@sjvans i looks like an issue with the query builder API:

```js
  const query = SELECT.from(OBJECTS, (o) => {
    o.OBJECT_TYPE, o.OBJECT_OID, o.SCHEMA_NAME, o.OBJECT_NAME;
    o?.view?.((t) => {
      t("*");
      t?.columns?.("*");
    });
  });
  console.log(JSON.stringify(query, null, 2));
```

yields:

```json5
{
      "SELECT": {
        "from": {
          "ref": [
            "OBJECTS"
          ]
        },
        "columns": [
          {
            "ref": [
              "OBJECT_TYPE"
            ]
          },
          {
            "ref": [
              "OBJECT_OID"
            ]
          },
          {
            "ref": [
              "SCHEMA_NAME"
            ]
          },
          {
            "ref": [
              "OBJECT_NAME"
            ]
          },
          { // from here on, the query looks very wrong 💥
            "ref": [
              "call" 
            ],
            "as": "undefined"
          },
          {
            "ref": [
              "raw"
            ]
          },
          {
            "ref": [
              "0"
            ]
          },
          {
            "ref": [
              null,
              "next",
              "done"
            ],
            "expand": [
              "*"
            ]
          }
        ]
      }
    }
```

→ `cds.infer` rightfully issues an error for the `ref: [ "call" ]` as there is no element `call`. Also the following `ref`s look also as something went wrong.

**Comment by ThePlenkov** [comment] 2024-09-10 11:39
@patricebender  may be we can label then it as a bug, not question, thanks!

**Comment by ThePlenkov** [comment] 2024-09-10 11:41
I also thought of something - why is it even optional? I mean if it's non-optional on the type level, then it's not even the error for TS. What could be the cases when  some column references are undefined in the projection function? 
Thanks!

**Comment by daogrady** [comment] 2024-09-11 06:10
@patricebender can you please assign this issue to someone who is familiar with the query builder api? Thanks!

**Comment by sjvans** [comment] 2024-09-11 07:51
i added it to the backlog

**Comment by David-Kunz** [comment] 2024-09-13 07:58
Hi,

The projection function only allows [specific operations](https://cap.cloud.sap/docs/node.js/cds-ql#columns):

- projections are single-argument arrow functions: a => { ... }
- with the argument as entity alias in column expressions: a.name
- with functions for nested projections: a.books (b => {...})
- with * as special case of that: b`.*` , and b.suppliers('*')
- with template strings for aliases: b.createdAt`as since`
- as well as for infix filters: b.suppliers`[city='Paris']`


It allows you to _statically_ define which columns of your entity you want to select. Technically, a JavaScript [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) is used to execute some logic once a certain field is accessed, e.g. in

```js
SELECT.from(MyEntity, e => { e.ID /* <-- field access */ })
```

There must not be any conditional operator and there shouldn't be a need for it. The corresponding TypeScript type should not complain that some properties might be undefined. It must be possible to follow every navigation of that entity, without checking for its existence. For example, it must be possible to write

```js
const result = await SELECT.from(OBJECTS, (o) => {
    o.OBJECT_TYPE, o.OBJECT_OID, o.SCHEMA_NAME, o.OBJECT_NAME,
    o.view((v) => {
        v('*'),
        v.columns('*');
      });
})
```

@daogrady , do you think we can make sure that the above code works w.r.t. TypeScript?

**Comment by daogrady** [comment] 2024-09-13 08:02
Hi David,

thanks for weighing in on this! I guess we should be able to express that properties, in the context of projections, are not optional. I will look into it.

Best,
Daniel

**Comment by ThePlenkov** [comment] 2024-09-24 10:18
A small update from my side:
this code works only with @cap-js/hana and will not work without it with @sap/hana-client. Probably another bug.
```
o.view((v) => {
        v('*');
        v.columns && v.columns('*');
      });
```
however what is working is this pattern:
```
o.view((v) => {
        v('*');
        v.columns!('*');
      });
```
we just simply need to use ! to mark it as always defined.

**Comment by daogrady** [comment] 2024-09-24 11:32
Hi,

I have made all properties non-optional within projections. That fix is dependent on another PR, so it is not yet available in `main`, but I hope we will see it as part of the next release. So I'll consider this as _fix merged_.
In the meantime, using the bang operator is a viable solution.

Best,
Daniel

**Closed by daogrady** 2024-09-24 11:32 UTC
Labels: bug
